// Resource record types, as understood by the underlying resolver.
exports.type = {
  A: 1,
  NS: 2,
  CNAME: 5,
  SOA: 6,
  PTR: 12,
  HINFO: 13,
  MX: 15,
  TXT: 16,
  SIG: 24,
  AAAA: 28,
  SRV: 33,
  NAPTR: 35,
  OPT: 41,
  TLSA: 52,
  SVCB: 64,
  HTTPS: 65,
  ANY: 255,
  URI: 256,
  CAA: 257
}

// Resolver status codes, indexed to match the values reported by the binding.
exports.status = {
  SUCCESS: 0,
  ENODATA: 1,
  EFORMERR: 2,
  ESERVFAIL: 3,
  ENOTFOUND: 4,
  ENOTIMP: 5,
  EREFUSED: 6,
  EBADQUERY: 7,
  EBADNAME: 8,
  EBADFAMILY: 9,
  EBADRESP: 10,
  ECONNREFUSED: 11,
  ETIMEOUT: 12,
  EOF: 13,
  EFILE: 14,
  ENOMEM: 15,
  EDESTRUCTION: 16,
  EBADSTR: 17,
  EBADFLAGS: 18,
  ENONAME: 19,
  EBADHINTS: 20,
  ENOTINITIALIZED: 21,
  ELOADIPHLPAPI: 22,
  EADDRGETNETWORKPARAMS: 23,
  ECANCELLED: 24,
  ESERVICE: 25,
  ENOSERVER: 26
}
